import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { config } from '../src/optimized/config.ts';
import { publishIndex, activeSnapshot } from '../src/optimized/index.ts';
import { fixtures } from '../src/evaluation/fixtures.ts';
import { askRag, NO_INFORMATION } from '../src/optimized/ask.ts';
import { createChromaClient } from '../src/shared/chroma.ts';
import { loadCounter } from '../src/optimized/tokens.ts';
import { chat, tokenizerProfile, modelInfo } from '../src/optimized/ollama.ts';
import type { StageMetric } from '../src/optimized/ollama.ts';

test('live: incremental index, removed chunks, failure leaves active snapshot, exact cache bypasses LLM', { skip: process.env.RAG_INTEGRATION !== '1', timeout: 240000 }, async () => {
  const base = config();
  const cfg = { ...base, root: path.join(base.root, 'integration', randomUUID()), collection: 'rag_integration' };
  const fixture = fixtures(100);
  const first = await publishIndex(fixture.manifest, cfg);
  const same = await publishIndex(fixture.manifest, cfg);
  assert.equal(same.reused, 100); assert.equal(same.embedded, 0);
  const removedId = fixture.manifest.chunks.at(-1)!.id;
  const reduced = { ...fixture.manifest, chunks: fixture.manifest.chunks.slice(0, -1), chunkCount: 99 };
  const third = await publishIndex(reduced, cfg);
  assert.equal(third.reused, 99);
  const collection = await createChromaClient(cfg).getCollection({ name: third.snapshot.collection });
  assert.deepEqual((await collection.get({ ids: [removedId] })).ids, []);
  await assert.rejects(publishIndex({ ...reduced, chunks: [] }, cfg), /empty/);
  assert.equal((await activeSnapshot(cfg)).id, third.snapshot.id);
  const answered = await askRag(fixture.cases[0].question, { config: cfg, mode: 'fast' });
  assert.equal(answered.status, 'answered');
  assert.match(answered.answer, /CLAVE-173/);
  assert.equal(answered.metrics.stages.length, 1);
  const cached = await askRag(fixture.cases[0].question, { config: cfg, mode: 'fast' });
  assert.equal(cached.metrics.cacheHit, true); assert.equal(cached.metrics.stages.length, 0);
  assert.equal(cached.metrics.searches.length, 0);
  const changedConfiguration = await askRag(fixture.cases[0].question, { config: { ...cfg, directTokens: cfg.directTokens + 1 }, mode: 'fast' });
  assert.equal(changedConfiguration.metrics.cacheHit, false);
  assert.equal(changedConfiguration.metrics.stages.length, 1);
  const changed = structuredClone(reduced);
  changed.chunks[0].text += ' A new maintenance note.';
  const fourth = await publishIndex(changed, cfg);
  assert.equal(fourth.embedded, 1); assert.equal(fourth.reused, 98);
  assert.notEqual(first.snapshot.id, fourth.snapshot.id);
  const afterChange = await askRag(fixture.cases[0].question, { config: cfg, mode: 'fast' });
  assert.equal(afterChange.metrics.cacheHit, false);
  assert.equal(afterChange.metrics.index, fourth.snapshot.id);
  const missing = fixture.cases.find(c => c.kind === 'absent')!;
  const absent = await askRag(missing.question, { config: cfg, mode: 'fast' });
  assert.equal(absent.status, 'insufficient');
  assert.equal(absent.answer, NO_INFORMATION);
  assert.deepEqual(absent.sources, []);
  const absentCached = await askRag(missing.question, { config: cfg, mode: 'fast' });
  assert.equal(absentCached.metrics.cacheHit, true);
  assert.equal(absentCached.metrics.stages.length, 0);
  const arithmetic = await askRag('1+1 ?', { config: cfg, cache: false });
  assert.equal(arithmetic.status, 'insufficient');
  assert.equal(arithmetic.answer, NO_INFORMATION);
  assert.deepEqual(arithmetic.sources, []);
  const recommendation = await askRag('De todas las versiones documentadas del Sistema Delta-41, cuál me recomiendas si necesito capacidad para 140 unidades? Justifica con los datos.', { config: cfg, cache: false });
  assert.equal(recommendation.status, 'answered');
  assert.match(recommendation.answer, /2025/);
  assert.ok(recommendation.sources.some(source => source.id === 'delta-0-current'));
  for (let attempt = 0; attempt < 2; attempt++) {
    const truncated = await askRag(fixture.cases[0].question, { config: { ...cfg, directTokens: 1 }, mode: 'fast' });
    assert.equal(truncated.status, 'truncated');
    assert.equal(truncated.metrics.cacheHit, false);
    assert.equal(truncated.metrics.stages.length, 1);
  }
});
test('live: local Qwen tokenizer matches server prompt token count within reserved margin', { skip: process.env.RAG_INTEGRATION !== '1', timeout: 120000 }, async () => {
  const cfg = config();
  const model = await modelInfo(cfg, cfg.model);
  cfg.model = model.name;
  if (cfg.tokenizerDir === 'auto') cfg.tokenizerDir = (await tokenizerProfile(cfg, model)).directory;
  const counter = await loadCounter(cfg.tokenizerDir);
  const stages: StageMetric[] = [];
  const system = 'Answer briefly.';
  const user = 'Responde OK. Unicode: válvula 水. Identifier: X-51.';
  await chat(cfg, 'tokenizer-check', system, user, 32, false, stages);
  assert.ok(stages[0].inputTokens > 0);
  assert.ok(Math.abs(counter.chat(system, user, false) - stages[0].inputTokens) <= 96);
});
